import React from 'react';
import { Account, Transaction } from '../types';
import { formatINR } from '../utils/riskEngine';
import { X, Printer, Copy, Check, ShieldAlert, Building2 } from 'lucide-react';

interface IncidentReportModalProps {
  transaction: Transaction | null;
  accountsMap: Map<string, Account>;
  isOpen: boolean;
  onClose: () => void;
}

export const IncidentReportModal: React.FC<IncidentReportModalProps> = ({
  transaction,
  accountsMap,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = React.useState(false);

  if (!isOpen || !transaction) return null;

  const sender = accountsMap.get(transaction.sender_id);
  const receiver = accountsMap.get(transaction.receiver_id);

  const reportId = `SAR-IND-2026-${transaction.transaction_id.slice(-4)}`;

  const handleCopy = () => {
    const reportText = `=== FRAUDCHAIN GUARD: AML / CYBER CRIME INCIDENT DOSSIER ===
Report Reference: ${reportId}
Transaction ID: ${transaction.transaction_id}
Amount: ₹${formatINR(transaction.amount)} (${transaction.type})
Timestamp: ${transaction.timestamp}
Calculated Risk: ${transaction.risk_score}/100 (${transaction.risk_band} Band)

[COUNTERPARTY DETAILS]
Originating Sender: ${sender?.name} (${sender?.id})
Sender Type & City: ${sender?.account_type} | ${sender?.city}
Beneficiary: ${receiver?.name} (${receiver?.id})
Beneficiary Type & KYC: ${receiver?.account_type} | ${receiver?.kyc_occupation}
Beneficiary Monthly KYC Limit: ₹${formatINR(receiver?.usual_monthly_credit_range[1] || 0)}

[TRIGGERED SIGNALS]
${transaction.detected_signals.map((s) => `- ${s.name} (+${s.points} pts): ${s.explanation}`).join('\n')}

[COMPLAINT DATA]
${transaction.complaint ? `1930 Portal Ref: ${transaction.complaint.portal_ref}
Complainant: ${transaction.complaint.complainant_name}
Category: ${transaction.complaint.category}
Division: ${transaction.complaint.cyber_cell_division}` : 'No external cyber portal complaint logged.'}

[EVIDENCE SUBMISSION]
${transaction.evidence ? `Status: ${transaction.evidence.status}
Category: ${transaction.evidence.purposeCategory}
Description: ${transaction.evidence.description}` : 'Pending response from account holder.'}

Analyst Disposition: ${transaction.investigation_status}
Generated by: FraudChain Guard Core AML Engine v4.2`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-sm animate-fadeIn">
      <div 
        className="bg-slate-900 border border-slate-700 rounded-2xl max-w-2xl w-full overflow-hidden shadow-2xl flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-4 bg-gradient-to-r from-slate-950 via-slate-900 to-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 flex items-center justify-center">
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white">Incident Dossier & Law Enforcement Export</h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                  {reportId}
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Official suspicious activity dispatch formatted for FIU-IND & State Cyber Cell
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Printable/Export Document Content */}
        <div className="p-5 overflow-y-auto max-h-[75vh] space-y-4 font-mono text-xs">
          {/* Header block */}
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
            <div className="flex justify-between border-b border-slate-800/80 pb-2 text-[11px] text-slate-400">
              <span>CONFIDENTIAL - BANK AML INTELLIGENCE REPORT</span>
              <span>CLASSIFICATION: RESTRICTED</span>
            </div>
            <div className="grid grid-cols-2 gap-2 text-slate-300">
              <div><strong className="text-slate-400">Transaction ID:</strong> {transaction.transaction_id}</div>
              <div><strong className="text-slate-400">Rail:</strong> {transaction.type}</div>
              <div><strong className="text-slate-400">Amount Intercepted:</strong> ₹{formatINR(transaction.amount)}</div>
              <div><strong className="text-slate-400">Risk Assessment:</strong> {transaction.risk_score}/100 ({transaction.risk_band})</div>
            </div>
          </div>

          {/* Parties */}
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
            <div className="text-[11px] font-bold text-cyan-400 uppercase tracking-wider">
              1. Counterparty Intelligence
            </div>
            <div className="space-y-1 text-slate-300 text-[11px]">
              <div><strong>Originating Sender:</strong> {sender?.name} ({sender?.id}) &mdash; {sender?.account_type}</div>
              <div><strong>Beneficiary Mule:</strong> {receiver?.name} ({receiver?.id}) &mdash; {receiver?.account_type} ({receiver?.kyc_occupation})</div>
              <div><strong>KYC Monthly Expected Limit:</strong> ₹{formatINR(receiver?.usual_monthly_credit_range[1] || 0)}</div>
              <div><strong>Beneficiary PAN:</strong> {receiver?.pan_masked} | City: {receiver?.city}</div>
            </div>
          </div>

          {/* Additive Signal Trail */}
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
            <div className="text-[11px] font-bold text-amber-400 uppercase tracking-wider">
              2. Algorithmic Signal Audit Trail
            </div>
            <div className="space-y-1.5 text-slate-300 text-[11px]">
              {transaction.detected_signals.map((sig) => (
                <div key={sig.code} className="flex justify-between border-b border-slate-900 pb-1">
                  <span>• {sig.name}</span>
                  <span className="text-amber-400 font-bold">+{sig.points} pts</span>
                </div>
              ))}
            </div>
          </div>

          {/* Disposition */}
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1 text-[11px] text-slate-300">
            <div className="text-cyan-400 font-bold uppercase">3. Case Status & Action</div>
            <div>Current Disposition: <strong className="text-white">{transaction.investigation_status}</strong></div>
            {transaction.notes.length > 0 && (
              <div className="pt-1 text-slate-400">
                Latest Note: "{transaction.notes[transaction.notes.length - 1].text}"
              </div>
            )}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium cursor-pointer"
          >
            Close
          </button>

          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer shadow-lg shadow-cyan-900/40"
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Formatted Report'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
